language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

install: composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --debug -c phpunit.xml

notifications:
  slack:
    secure: VLeuaY2r3F6Csja1OkkjJSLyapqaEodRtK2lDJ0G+XzZHLE9ys6CV2CIt/JBMTqWYjPFhF43v/gB7bvZQ5X4UKGEYAsmJLootNknMx0QHG5c7N6iqT7yDE80WonngKKtdMNXiKmI7H3Ezi1BH0+f6V9qpJx5eFxfpU27kJzE3XhH2dIz21nCD0qS7gNQTExz47xl8cr8xHQx/nv78IhO8XDoDd+UdEMIhRr9PR0hh+6yYBpWtQCraRJEydniarqkqCUbDXBQLT73+yj5WzSydE23GMdldx6AZ8pdANsqSLX28KZBLkUfSC1s+cQ/2/kzWjhZPXR+aNYt3sWD0IGxYWRtEQOcaufI8ePaoMhbFMZLSLfqXymFfed06BUaT1xlaOShWNm+5U4heOaYIh6O2z+n7E4TivEhGL0F+DDJuxUafgJCK04ayL2bXV/Tx9KIjqG4jTSzs8vW7g6ipKvi7sM6uDVkQqQx3DmtHm4cxvlRM38OKB41tHAQ+lWe4Bb4yTSvR952w3lIIop/WGV1T6MRg3M1cYpx/YqHaCYzhITspcJBmFwNdosxguG9O4N0D3ZajJxpu9dW7/usN3uZEohxITAAVZLeOB7JpXcrxHZ264ExFxAkGJLD9q0hN0gmYz6VXof2wNgs75Q/ytD49tXm5Kv7dqD7UtQfyUQRKsI=
